# Generated by Django 4.1.3 on 2022-11-15 11:27

from django.db import migrations, models
import employee.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10, validators=[employee.validations.validate_number])),
                ('location', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
